<?php

/**
 * Countries used across the activities system.
 * Key = canonical country name stored in DB.
 * 'flag' = emoji flag (rendered natively on all modern OS).
 * 'currency' = ISO 4217 3-letter code.
 */
return [
    'United Arab Emirates' => ['flag' => '🇦🇪', 'currency' => 'AED'],
    'Afghanistan'          => ['flag' => '🇦🇫', 'currency' => 'AFN'],
    'Albania'              => ['flag' => '🇦🇱', 'currency' => 'ALL'],
    'Algeria'              => ['flag' => '🇩🇿', 'currency' => 'DZD'],
    'Argentina'            => ['flag' => '🇦🇷', 'currency' => 'ARS'],
    'Armenia'              => ['flag' => '🇦🇲', 'currency' => 'AMD'],
    'Australia'            => ['flag' => '🇦🇺', 'currency' => 'AUD'],
    'Austria'              => ['flag' => '🇦🇹', 'currency' => 'EUR'],
    'Azerbaijan'           => ['flag' => '🇦🇿', 'currency' => 'AZN'],
    'Bahrain'              => ['flag' => '🇧🇭', 'currency' => 'BHD'],
    'Bangladesh'           => ['flag' => '🇧🇩', 'currency' => 'BDT'],
    'Belgium'              => ['flag' => '🇧🇪', 'currency' => 'EUR'],
    'Bolivia'              => ['flag' => '🇧🇴', 'currency' => 'BOB'],
    'Brazil'               => ['flag' => '🇧🇷', 'currency' => 'BRL'],
    'Bulgaria'             => ['flag' => '🇧🇬', 'currency' => 'BGN'],
    'Cambodia'             => ['flag' => '🇰🇭', 'currency' => 'KHR'],
    'Canada'               => ['flag' => '🇨🇦', 'currency' => 'CAD'],
    'Chile'                => ['flag' => '🇨🇱', 'currency' => 'CLP'],
    'China'                => ['flag' => '🇨🇳', 'currency' => 'CNY'],
    'Colombia'             => ['flag' => '🇨🇴', 'currency' => 'COP'],
    'Croatia'              => ['flag' => '🇭🇷', 'currency' => 'EUR'],
    'Czech Republic'       => ['flag' => '🇨🇿', 'currency' => 'CZK'],
    'Denmark'              => ['flag' => '🇩🇰', 'currency' => 'DKK'],
    'Egypt'                => ['flag' => '🇪🇬', 'currency' => 'EGP'],
    'Ethiopia'             => ['flag' => '🇪🇹', 'currency' => 'ETB'],
    'Finland'              => ['flag' => '🇫🇮', 'currency' => 'EUR'],
    'France'               => ['flag' => '🇫🇷', 'currency' => 'EUR'],
    'Georgia'              => ['flag' => '🇬🇪', 'currency' => 'GEL'],
    'Germany'              => ['flag' => '🇩🇪', 'currency' => 'EUR'],
    'Ghana'                => ['flag' => '🇬🇭', 'currency' => 'GHS'],
    'Greece'               => ['flag' => '🇬🇷', 'currency' => 'EUR'],
    'Hungary'              => ['flag' => '🇭🇺', 'currency' => 'HUF'],
    'India'                => ['flag' => '🇮🇳', 'currency' => 'INR'],
    'Indonesia'            => ['flag' => '🇮🇩', 'currency' => 'IDR'],
    'Iran'                 => ['flag' => '🇮🇷', 'currency' => 'IRR'],
    'Iraq'                 => ['flag' => '🇮🇶', 'currency' => 'IQD'],
    'Ireland'              => ['flag' => '🇮🇪', 'currency' => 'EUR'],
    'Israel'               => ['flag' => '🇮🇱', 'currency' => 'ILS'],
    'Italy'                => ['flag' => '🇮🇹', 'currency' => 'EUR'],
    'Japan'                => ['flag' => '🇯🇵', 'currency' => 'JPY'],
    'Jordan'               => ['flag' => '🇯🇴', 'currency' => 'JOD'],
    'Kazakhstan'           => ['flag' => '🇰🇿', 'currency' => 'KZT'],
    'Kenya'                => ['flag' => '🇰🇪', 'currency' => 'KES'],
    'Kuwait'               => ['flag' => '🇰🇼', 'currency' => 'KWD'],
    'Lebanon'              => ['flag' => '🇱🇧', 'currency' => 'LBP'],
    'Malaysia'             => ['flag' => '🇲🇾', 'currency' => 'MYR'],
    'Maldives'             => ['flag' => '🇲🇻', 'currency' => 'MVR'],
    'Mauritius'            => ['flag' => '🇲🇺', 'currency' => 'MUR'],
    'Mexico'               => ['flag' => '🇲🇽', 'currency' => 'MXN'],
    'Morocco'              => ['flag' => '🇲🇦', 'currency' => 'MAD'],
    'Myanmar'              => ['flag' => '🇲🇲', 'currency' => 'MMK'],
    'Nepal'                => ['flag' => '🇳🇵', 'currency' => 'NPR'],
    'Netherlands'          => ['flag' => '🇳🇱', 'currency' => 'EUR'],
    'New Zealand'          => ['flag' => '🇳🇿', 'currency' => 'NZD'],
    'Nigeria'              => ['flag' => '🇳🇬', 'currency' => 'NGN'],
    'Norway'               => ['flag' => '🇳🇴', 'currency' => 'NOK'],
    'Oman'                 => ['flag' => '🇴🇲', 'currency' => 'OMR'],
    'Pakistan'             => ['flag' => '🇵🇰', 'currency' => 'PKR'],
    'Peru'                 => ['flag' => '🇵🇪', 'currency' => 'PEN'],
    'Philippines'          => ['flag' => '🇵🇭', 'currency' => 'PHP'],
    'Poland'               => ['flag' => '🇵🇱', 'currency' => 'PLN'],
    'Portugal'             => ['flag' => '🇵🇹', 'currency' => 'EUR'],
    'Qatar'                => ['flag' => '🇶🇦', 'currency' => 'QAR'],
    'Romania'              => ['flag' => '🇷🇴', 'currency' => 'RON'],
    'Russia'               => ['flag' => '🇷🇺', 'currency' => 'RUB'],
    'Saudi Arabia'         => ['flag' => '🇸🇦', 'currency' => 'SAR'],
    'Senegal'              => ['flag' => '🇸🇳', 'currency' => 'XOF'],
    'Seychelles'           => ['flag' => '🇸🇨', 'currency' => 'SCR'],
    'Singapore'            => ['flag' => '🇸🇬', 'currency' => 'SGD'],
    'South Africa'         => ['flag' => '🇿🇦', 'currency' => 'ZAR'],
    'South Korea'          => ['flag' => '🇰🇷', 'currency' => 'KRW'],
    'Spain'                => ['flag' => '🇪🇸', 'currency' => 'EUR'],
    'Sri Lanka'            => ['flag' => '🇱🇰', 'currency' => 'LKR'],
    'Sweden'               => ['flag' => '🇸🇪', 'currency' => 'SEK'],
    'Switzerland'          => ['flag' => '🇨🇭', 'currency' => 'CHF'],
    'Tanzania'             => ['flag' => '🇹🇿', 'currency' => 'TZS'],
    'Thailand'             => ['flag' => '🇹🇭', 'currency' => 'THB'],
    'Tunisia'              => ['flag' => '🇹🇳', 'currency' => 'TND'],
    'Turkey'               => ['flag' => '🇹🇷', 'currency' => 'TRY'],
    'Uganda'               => ['flag' => '🇺🇬', 'currency' => 'UGX'],
    'Ukraine'              => ['flag' => '🇺🇦', 'currency' => 'UAH'],
    'United Kingdom'       => ['flag' => '🇬🇧', 'currency' => 'GBP'],
    'United States'        => ['flag' => '🇺🇸', 'currency' => 'USD'],
    'Uzbekistan'           => ['flag' => '🇺🇿', 'currency' => 'UZS'],
    'Vietnam'              => ['flag' => '🇻🇳', 'currency' => 'VND'],
    'Zimbabwe'             => ['flag' => '🇿🇼', 'currency' => 'ZWL'],
];
