import { chromium } from 'playwright';
const url = process.argv[2];
const out = process.argv[3];
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport:{width:1366,height:900} })).newPage();
await page.goto(url, { waitUntil:'networkidle' }).catch(()=>{});
await page.waitForTimeout(2500);
await page.screenshot({ path: out, fullPage: false });
await browser.close();
console.log('shot ->', out);
