<?php

namespace App\Mail;

use App\Models\EsimOrder;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * The customer's eSIM, sent by GoTrips.
 *
 * MontyeSIM sends its own QR email on assign, but we cannot see whether it
 * arrived, and it carries their branding rather than ours. Since the
 * installation credentials are readable from the order detail endpoint, we
 * send our own copy — so a customer who paid always has an eSIM in their inbox
 * from the company they bought it from.
 *
 * The QR image is generated by a Google Charts URL rather than a local library
 * so it needs no extra dependency; the activation details are also printed as
 * text underneath for manual installation, which every device supports.
 */
class EsimQrMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public EsimOrder $order,
        public ?string $activationCode = null,
        public ?string $smdpAddress = null,
        public ?string $matchingId = null,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Your eSIM for ' . ($this->order->country_name ?: 'your trip') . ' — ' . $this->order->order_reference,
        );
    }

    public function content(): Content
    {
        // The LPA string is what an eSIM QR encodes. Prefer the provider's own
        // activation_code; fall back to composing it from its parts.
        $lpa = $this->activationCode
            ?: ($this->smdpAddress && $this->matchingId
                ? 'LPA:1$' . $this->smdpAddress . '$' . $this->matchingId
                : null);

        return new Content(
            view: 'emails.esim-qr',
            with: [
                'order'       => $this->order,
                'lpa'         => $lpa,
                'smdpAddress' => $this->smdpAddress,
                'matchingId'  => $this->matchingId,
                'qrUrl'       => $lpa
                    ? 'https://chart.googleapis.com/chart?cht=qr&chs=320x320&chld=M|1&chl=' . urlencode($lpa)
                    : null,
            ],
        );
    }
}
